platform :ios, '8.1'

# RestKit
pod 'RestKit',         '~> 0.24.0'
pod 'RestKit/Testing', '~> 0.24.0'

# JSONSyntaxHighlight
pod 'JSONSyntaxHighlight'

# UICKeyChainStore
pod 'UICKeyChainStore'

# UIAlertView-Blocks
pod 'UIAlertView-Blocks', '~> 1.0'
